book-manager/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace book_manager.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public int YearEdition { get; set; }
        public decimal Value { get; set; }

         /* Entity Framework class association,
         he knows that GenderId is a foreign key
         in Book class. */
        public Gender Gender { get; set; }
        public int GenderId { get; set; }
    }
}

book-manager/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees.ExpressionBuilder;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using book_manager.DataAccess;
using book_manager.Infra;
using book_manager.Models;
using book_manager.ViewModels;

namespace book_manager.Controllers
{
    public class BooksController : Controller
    {
        private BookContext db = new BookContext();

        // GET: Books/Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: Books/List -> JSON with all books
        public JsonResult List(PaginationParameters paginationParameters)
        {
            var books = db.Books.AsQueryable();
            var total = books.Count();

            if (!string.IsNullOrWhiteSpace(paginationParameters.SearchPhrase))
            {
                int year = 0;
                int.TryParse(paginationParameters.SearchPhrase, out year);

                decimal value = 0;
                decimal.TryParse(paginationParameters.SearchPhrase, out value);

                books = books.Where("Title.Contains(@0) OR Author.Contains(@0) OR YearEdition == @1 OR Value == @2", paginationParameters.SearchPhrase, year, value);
            }

            var paginatedBooks = books.OrderBy(paginationParameters.OrderedField).Skip((paginationParameters.Current - 1) * paginationParameters.RowCount).Take(paginationParameters.RowCount);

            return Json(new FilteredData()
            {
                current = paginationParameters.Current,
                rowCount = paginationParameters.RowCount,
                rows = paginatedBooks,
                total = total

            }, JsonRequestBehavior.AllowGet);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Book book = db.Books.Find(id);

            if (book == null)
                return HttpNotFound();
            
            return PartialView(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name");
            return PartialView();
        }

        // POST: Books/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Create([Bind(Include = "Id,Title,Author,YearEdition,Value,GenderId")] Book book)
        {
            object response = null;

            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                response = new { result = true, message = "Book registered successfully!" };
            }
            else
            {
                IEnumerable<ModelError> errors = ModelState.Values.SelectMany(item => item.Errors);
                response = new { result = false, message = errors };
            }

            return Json(response);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Book book = db.Books.Find(id);

            if (book == null)
                return HttpNotFound();
            
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", book.GenderId);
            return PartialView(book);
        }

        // POST: Books/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit([Bind(Include = "Id,Title,Author,YearEdition,Value,GenderId")] Book book)
        {
            object response = null;

            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                response = new { result = true, message = "Book edited successfully!" };
            }
            else
            {
                IEnumerable<ModelError> errors = ModelState.Values.SelectMany(item => item.Errors);
                response = new { result = false, message = errors };
            }

            return Json(response);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Book book = db.Books.Find(id);

            if (book == null)
                return HttpNotFound();
            
            return PartialView(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            object response = null;

            try
            {
                Book book = db.Books.Find(id);
                db.Books.Remove(book);
                db.SaveChanges();
                response = new { result = true, message = "Book removed successfully!" };
            }
            catch(Exception ex)
            {
                response = new { result = false, message = ex.Message };
            }

            return Json(response);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

book-manager/Views/Books/Create.cshtml
@model book_manager.Models.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { id= "createForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearEdition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearEdition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearEdition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderId, "GenderId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/project/sendForm.js"></script>

book-manager/Views/Books/Delete.cshtml
@model book_manager.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gender.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearEdition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearEdition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Books", FormMethod.Post, new { id = "createForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="button" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to list", "Index");
        </div>
    }
</div>

<script src="~/Scripts/project/sendForm.js"></script>

book-manager/Views/Books/Details.cshtml
@model book_manager.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Gender.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearEdition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearEdition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
</p>

book-manager/Views/Books/Edit.cshtml
@model book_manager.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { id = "createForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearEdition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.YearEdition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.YearEdition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderId, "GenderId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/project/sendForm.js"></script>

book-manager/Views/Books/Index.cshtml
@model IEnumerable<book_manager.Models.Book>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="#" data-action='Create' class="btn btn-success">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Novo Livro
    </a>
</p>

<table id="booksGrid">
    <thead>
        <tr>
            <th data-column-id="Title" data-order="asc">Title</th>
            <th data-column-id="Author">Author</th>
            <th data-column-id="YearEdition">Year of Edition</th>
            <th data-column-id="Value">Value</th>
            <th data-formatter="Actions"></th>
        </tr>
    </thead>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="modalContent"></div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.bootgrid.js"></script>
    <script src="~/Scripts/project/controlBootgrid.js"></script>

    <script type="text/javascript">
        $(document).ready(configureControls);

        const listUrl = "@Url.Action("List")";        
    </script>

}

book-manager/Views/Books/_List.cshtml
@model book_manager.Models.Book

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Gender.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearEdition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Gender.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearEdition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>